routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'namespace' => 'Website', // it is added in controller function name
    'prefix' => '', //it is added in url
    'as' => 'website.' //route name
], function () {
    Route::get('', 'HomeController@index')->name('home');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::post('contact/email','ContactController@contactEmail')->name('contactEmail');

    Route::get('login', 'LoginController@index')->name('login');
    Route::get('job_details/{id}', 'JobController@index')->name('job_details');

    Route::get('login','LoginController@index')->name('login');
    Route::get('registration', 'RegistrationController@index')->name('registration');
    Route::post('store/candidate','RegistrationController@storeCandidate')->name('storeCandidate');
    Route::post('authenticate','LoginController@authenticate')->name('authenticate');
    Route::get('varify/otp','RegistrationController@otpForm')->name('otpForm');
    Route::post('varify/otp/success','RegistrationController@varifyOtp')->name('varifyOtp');

    // Search Section
    Route::post('view/searchjobs','SearchController@index')->name('searchResult');
    Route::get('view/searchjobs/{title}/{category_id}','SearchController@searchResult')->name('viewSearchResult');

    // Cms
    Route::get('cms/{id}','CmsController@page')->name('cms');

    // Enquiry Section
    Route::get('enquiry','EnquiryController@index')->name('enquiry');
    Route::post('store/enquiry','EnquiryController@storeEnquiry')->name('storeEnquiry');

    // Browse Jobs
    Route::get('browse/jobs','BrowseJobController@index')->name('browseJobs');

    // Browse Categories
    Route::get('browse/categories','BrowseCategoryController@index')->name('browseCategories');
    Route::get('browse/category/jobs/{id}','BrowseCategoryController@categoryJobs')->name('browseCategoryJobs');
    // Job Alert
    Route::get('job/alerts','JobAlertController@index')->name('jobAlerts');

    Route::group(['middleware' => 'candidate.auth'], function () {

      Route::get('logout', 'LoginController@logout')->name('logout');
      Route::get('apply/job/{id}', 'JobController@applyJob')->name('applyJob');

      Route::get('take/appointment','AppointmentController@index')->name('takeAppointment');
      Route::post('get/city/partners','AppointmentController@getCityPartners')->name('getCityPartners');
      Route::post('store/appointment','AppointmentController@storeAppointment')->name('storeAppointment');

      Route::get('book/interview','BookInterviewController@index')->name('bookInterview');
      Route::post('get/category/jobs','BookInterviewController@getCategoryJobs')->name('getCategoryJobs');
      Route::post('store/book/interview','BookInterviewController@storeBookInterview')->name('storeBookInterview');

    });
});



Route::group([
    'namespace' => 'Admin', // it is added in controller function name
    'prefix' => 'admin', //it is added in url
    'as' => 'admin.' //route name
], function () {
    Route::get('','LoginController@loginForm');
    Route::post('authenticate', 'LoginController@authenticate')->name('authenticate');

    Route::get('forgot/password', 'ForgotPasswordController@forgotPasswordEmail')->name('forgotPassword');
    Route::post('verify/email', 'ForgotPasswordController@verifyForgotPasswordEmail')->name('verifyEmail');
    Route::get('reset/password/{token}', 'ForgotPasswordController@resetPasswordForm')->name('resetPasswordForm');
    Route::post('reset/password/success', 'ForgotPasswordController@resetPassword')->name('resetPassword');


    Route::group(['middleware' => 'admin.auth'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('logout','LoginController@logout')->name('logout');

        Route::get('profile','ProfileController@profile')->name('profile');
        Route::post('update/Profile','ProfileController@updateProfile')->name('updateProfile');

        Route::get('change/password','ChangePasswordController@changePasswordForm')->name('changePasswordForm');
        Route::post('update/password','ChangePasswordController@updatePassword')->name('updatePassword');

        // job posts
        Route::get('job', 'JobPostController@index')->name('job');
        Route::get('add/job', 'JobPostController@addJob')->name('addJob');
        Route::post('store/job', 'JobPostController@storeJob')->name('storeJob');
        Route::get('edit/job/{id}', 'JobPostController@editJob')->name('editJob');
        Route::post('update/job/{id}', 'JobPostController@updateJob')->name('updateJob');
        Route::post('delete/job', 'JobPostController@deleteJob')->name('deleteJob');
        //Route::post('delete/all/jobs', 'JobPostController@deleteAll')->name('deleteAll')->middleware('permission:delete.job');
        Route::get('view/job/candidates/{id}','JobPostController@viewJobCandidates')->name('viewJobCandidates');
        Route::post('sendmail/job/candidates', 'JobPostController@approveJobCandidate')->name('approveJobCandidate');
        Route::post('delete/job/candidates', 'JobPostController@deleteJobCandidate')->name('deleteJobCandidate');
        Route::get('job/candidateresult/{id}','JobPostController@viewJobCandidateResult')->name('viewJobCandidateResult');
        Route::post('changestatus/job', 'JobPostController@changeStatus')->name('changeStatusJob');

        Route::get('upload/job/excel','JobPostController@uploadJobsExcel')->name('uploadJobsExcel');
        Route::post('store/job/excel','JobPostController@storeJobsExcel')->name('storeJobsExcel');

        Route::get('view/job/openings/{id}', 'JobPostController@viewJobOpenings')->name('viewJobOpenings');
        Route::get('add/job/opening/{id}', 'JobPostController@addJobOpening')->name('addJobOpening');
        Route::post('delete/job/opening', 'JobPostController@deleteJobOpening')->name('deleteJobOpening');
        Route::post('store/job/opening', 'JobPostController@storeJobOpening')->name('storeJobOpening');

        //candidate section
        Route::get('candidate','CandidateController@index')->name('candidate');
        Route::post('delete/candidate', 'CandidateController@deleteCandidate')->name('deleteCandidate');
        Route::get('view/candidate/{id}','CandidateController@viewCandidate')->name('viewCandidate');
        Route::post('changestatus/candidate', 'CandidateController@changeStatus')->name('changeStatusCandidate');

        Route::get('candidate/jobs/{id}','CandidateController@jobs')->name('viewCandidateJobs');
        Route::post('delete/candidate/job', 'CandidateController@deleteCandidateJob')->name('deleteCandidateJob');
        Route::post('sendmail/candidate/job', 'CandidateController@approveCandidateJob')->name('approveCandidateJob');
        Route::get('candidate/jobresult/{id}','CandidateController@viewCandidateJobResult')->name('viewCandidateJobResult');

        Route::get('candidate/appointments/{id}','CandidateController@appointments')->name('viewCandidateAppointments');
        Route::post('delete/candidate/appointment', 'CandidateController@deleteAppointment')->name('deleteCandidateAppointment');
        Route::post('approve/candidate/appointments','CandidateController@approveCandidateAppointments')->name('approveCandidateAppointments');
        Route::get('view/appointment/{id}','CandidateController@viewAppointment')->name('viewAppointment');

        //Cms
        Route::get('cms', 'CmsController@index')->name('cms');
        Route::get('add/cms', 'CmsController@addCms')->name('addCms');
        Route::post('store/cms', 'CmsController@storeCms')->name('storeCms');
        Route::get('edit/cms/{id}', 'CmsController@editCms')->name('editCms');
        Route::post('update/cms/{id}', 'CmsController@updateCms')->name('updateCms');

        //Categories
        Route::get('category', 'CategoryController@index')->name('category');
        Route::get('add/category', 'CategoryController@addCategory')->name('addCategory');
        Route::post('store/category', 'CategoryController@storeCategory')->name('storeCategory');
        Route::get('edit/category/{id}', 'CategoryController@editCategory')->name('editCategory');
        Route::post('update/category/{id}', 'CategoryController@updateCategory')->name('updateCategory');
        Route::post('delete/category', 'CategoryController@deleteCategory')->name('deleteCategory');
        Route::post('changestatus/category', 'CategoryController@changeStatus')->name('changeStatusCategory');

        //Enquiry
        Route::get('enquiry','EnquiryController@index')->name('enquiry');
        Route::post('delete/enquiry', 'EnquiryController@deleteEnquiry')->name('deleteEnquiry');

        //City
        Route::get('city','CityController@index')->name('city');
        Route::post('delete/city', 'CityController@deleteCity')->name('deleteCity');
        Route::post('delete/all/cities', 'CityController@deleteAllCities')->name('deleteAllCities');
        Route::get('upload/city/excel','CityController@uploadCitiesExcel')->name('uploadCitiesExcel');
        Route::post('store/city/excel','CityController@storeCitiesExcel')->name('storeCitiesExcel');

        Route::get('view/city/partners/{id}', 'CityController@viewCityPartners')->name('viewCityPartners');
        Route::get('add/city/partner/{id}', 'CityController@addCityPartner')->name('addCityPartner');
        Route::post('delete/city/partner', 'CityController@deleteCityPartner')->name('deleteCityPartner');

resources/views/invoice.blade.php
<h2 style="text-align: center">APPOINTMENT LETTER</h2><br>
<br>

{{ date('d-m-Y') }}<br><br>

Dear {{ $appointment->candidate->name }},<br><br>

Your appointment has been confirmed by admin. <br><br>

Appointment Details : <br/><br/>

<b>City Name :</b> {{ $appointment->city->name }} <br><br>

<b>Categories :</b> {{ $appointment->categories }} <br><br>

<b>Date :</b> {{ $appointment->date }} <br><br>

<b>Start Time :</b> {{ $appointment->start_time }} <br><br>

<b>Total Experiences :</b> {{ $appointment->total_experiences }} <br><br>

<b>Job Location :</b> {{ $appointment->joblocations }} <br><br>

<b>Country :</b> {{ $appointment->country }} <br><br>


Please come with following documents.<br><br>

1. Leaving Certificate<br>
2. SSC Certificate<br>
3. HSC Certificate<br>
3. Adhar Card<br>
4. Election Card<br><br>

<p></p>Sincerely,<br>
Admin,<br>
Job Board</p>

resources/views/login_mainlayout.blade.php
<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.2
Version: 3.3.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8"/>
    <title>  @yield('title', 'Admin Panel' )| Amigos Management F.Z.C</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/simple-line-icons/simple-line-icons.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/css/components.min.css')}}" rel="stylesheet" id="style_components" type="text/css" />
    <link href="{{asset('assets/global/css/plugins.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/pages/css/login.min.css')}}" rel="stylesheet" type="text/css" />

    <link rel="shortcut icon" href="{{ asset('assets/img/amigos - divyang icon.png') }}">
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGO -->
<div class="logo">
    <a href="{{ route('admin.dashboard') }}">
        <img width="150px" height="100px" src="{{ asset('assets/img/amigos - divyang.png') }}" alt=""/>
        {{--<h2 style="color:#fff">JobBoard</h2>--}}
    </a>
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div class="content">
@yield('content')
</div>
<div class="copyright">
    2017 © MTAJ solutions. Amigos Management F.Z.C Admin Dashboard.
</div>
<!-- END LOGIN -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="{{ asset('assets/js/respond.min.js') }}"></script>
<script src="{{ asset('assets/js/excanvas.min.js') }}"></script>
<![endif]-->
<script src="{{ asset('assets/js/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/jquery-migrate.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/jquery.blockui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/jquery.cokie.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/uniform/jquery.uniform.min.js') }}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{ asset('assets/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{ asset('assets/js/metronic.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/layout/scripts/layout.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/layout/scripts/demo.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/login.js') }}'" type="text/javascript"></script>


<link rel="stylesheet" type="text/css" href="{{ asset('assets/sweetalert/sweetalert2.css') }}"/>
<script type="text/javascript" src="{{ asset('assets/sweetalert/sweetalert2.js') }}"></script>

<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function() {
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        Login.init();
        Demo.init();
    });
</script>


@if(Session::has('error'))

    <script>
        swal({
            title: 'Oops!',
            text: '{{ Session::get('error') }}',
            type: 'error',
            confirmButtonText: 'Ok'
        })
    </script>

@endif


@if(Session::has('info'))

    <script>
        swal({
            title: 'Success',
            text: '{{ Session::get('info') }}',
            timer: 3000
        }).then(
            function () {},
// handling the promise rejection
            function (dismiss) {
                if (dismiss === 'timer') {
                    console.log('I was closed by the timer')
                }
            }
        )

    </script>

@endif

<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

resources/views/sidebar.blade.php
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
            <li class="sidebar-toggler-wrapper">
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->


<div class="panel-detail">
    <span class="badge badge-primary" style="font-size: 18px!important;"> Admin Panel</span>
</div>
                <!-- END SIDEBAR TOGGLER BUTTON -->
            </li>
            <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
            <li class="sidebar-search-wrapper">
                <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                <!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
                <!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
                <form class="sidebar-search " action="#" method="POST">
                  <a href="javascript:;" class="remove">
                        <i class="icon-close"></i>
                    </a>
                </form>
                <!-- END RESPONSIVE QUICK SEARCH FORM -->
            </li>
            <!-- BEGIN Dashboard LINK -->
            <li @if (Request::segment('2') === 'dashboard' || Request::segment('3') === 'dashboard') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.dashboard')  }}"><i class="icon-paper-plane"></i><span class="title"> Dashboard  </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'cms' || Request::segment('3') === 'cms') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.cms')  }}"><i class="icon-paper-plane"></i><span class="title"> CMS  </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'category' || Request::segment('3') === 'category') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.category')  }}"><i class="icon-paper-plane"></i><span class="title"> Category  </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'city' || Request::segment('3') === 'city') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.city')  }}"><i class="icon-paper-plane"></i><span class="title"> City  </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'joblocation' || Request::segment('3') === 'joblocation') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.jobLocation')  }}"><i class="icon-paper-plane"></i><span class="title"> Job Location </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'job' || Request::segment('3') === 'job') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.job')  }}"><i class="icon-paper-plane"></i><span class="title"> Job </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'candidate' || Request::segment('3') === 'candidate') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.candidate')  }}"><i class="icon-paper-plane"></i><span class="title"> Candidate </span>
                </a>
            </li>

            {{-- <li @if (Request::segment('2') === 'appointment' || Request::segment('3') === 'appointment') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.appointment')  }}"><i class="icon-paper-plane"></i>
                    <span class="title"> Appointment </span>
                </a>
            </li> --}}

            <li class="nav-item  @if (Request::segment('2') === 'appointment' || Request::segment('3') === 'appointment') active open @endif">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-paper-plane"></i>
                    <span class="title">Appointment</span>
                    @if (Request::segment('2') === 'appointment' || Request::segment('3') === 'appointment')
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    @endif
                </a>
                <ul class="sub-menu">
                    <li class="nav-item @if (Request::segment('3') === 'pending') active open @endif">
                        <a href="{{ route('admin.appointment',['id' => 'pending']) }}" class="nav-link ">
                            <span class="title">Pending</span>
                        </a>
                    </li>
                    <li class="nav-item @if (Request::segment('3') === 'approved') active open @endif">
                        <a href="{{ route('admin.appointment',['id' => 'approved']) }}" class="nav-link ">
                            <span class="title">Approved</span>
                        </a>
                    </li>
                </ul>
            </li>


            <li @if (Request::segment('2') === 'enquiry' || Request::segment('3') === 'enquiry') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.enquiry')  }}"><i class="icon-paper-plane"></i><span class="title"> Enquiry </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'partner' || Request::segment('3') === 'partner') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.clientPartners')  }}"><i class="icon-paper-plane"></i><span class="title"> Clients & Partners </span>
                </a>
            </li>

            <li @if (Request::segment('2') === 'testimonial' || Request::segment('3') === 'testimonial') class="active" @endif data-container="body" data-placement="right" data-html="true">
                <a href="{{ route('admin.testimonial')  }}"><i class="icon-paper-plane"></i><span class="title"> Testimonials </span>
                </a>
            </li>

        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
</div>
<!-- END SIDEBAR -->