routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'namespace' => 'Website', // it is added in controller function name
    'prefix' => '', //it is added in url
    'as' => 'website.' //route name
], function () {
    Route::get('', 'HomeController@index')->name('home');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::post('contact/email','ContactController@contactEmail')->name('contactEmail');

    Route::get('login', 'LoginController@index')->name('login');
    Route::get('job_details/{id}', 'JobController@index')->name('job_details');

    Route::get('login','LoginController@index')->name('login');
    Route::get('registration', 'RegistrationController@index')->name('registration');
    Route::post('store/candidate','RegistrationController@storeCandidate')->name('storeCandidate');
    Route::post('authenticate','LoginController@authenticate')->name('authenticate');
    Route::get('varify/otp','RegistrationController@otpForm')->name('otpForm');
    Route::post('varify/otp/success','RegistrationController@varifyOtp')->name('varifyOtp');

    // Search Section
    Route::post('view/searchjobs','SearchController@index')->name('searchResult');
    Route::get('view/searchjobs/{title}/{category_id}','SearchController@searchResult')->name('viewSearchResult');

    // Cms
    Route::get('cms/{id}','CmsController@page')->name('cms');

    // Enquiry Section
    Route::get('enquiry','EnquiryController@index')->name('enquiry');
    Route::post('store/enquiry','EnquiryController@storeEnquiry')->name('storeEnquiry');

    // Browse Jobs
    Route::get('browse/jobs','BrowseJobController@index')->name('browseJobs');

    // Browse Categories
    Route::get('browse/categories','BrowseCategoryController@index')->name('browseCategories');
    Route::get('browse/category/jobs/{id}','BrowseCategoryController@categoryJobs')->name('browseCategoryJobs');
    // Job Alert
    Route::get('job/alerts','JobAlertController@index')->name('jobAlerts');

    Route::group(['middleware' => 'candidate.auth'], function () {

      Route::get('logout', 'LoginController@logout')->name('logout');
      Route::get('apply/job/{id}', 'JobController@applyJob')->name('applyJob');

      Route::get('take/appointment','AppointmentController@index')->name('takeAppointment');
      Route::post('get/city/partners','AppointmentController@getCityPartners')->name('getCityPartners');
      Route::post('store/appointment','AppointmentController@storeAppointment')->name('storeAppointment');

      Route::get('book/interview','BookInterviewController@index')->name('bookInterview');
      Route::post('get/category/jobs','BookInterviewController@getCategoryJobs')->name('getCategoryJobs');
      Route::post('store/book/interview','BookInterviewController@storeBookInterview')->name('storeBookInterview');

    });
});



Route::group([
    'namespace' => 'Admin', // it is added in controller function name
    'prefix' => 'admin', //it is added in url
    'as' => 'admin.' //route name
], function () {
    Route::get('','LoginController@loginForm');
    Route::post('authenticate', 'LoginController@authenticate')->name('authenticate');

    Route::get('forgot/password', 'ForgotPasswordController@forgotPasswordEmail')->name('forgotPassword');
    Route::post('verify/email', 'ForgotPasswordController@verifyForgotPasswordEmail')->name('verifyEmail');
    Route::get('reset/password/{token}', 'ForgotPasswordController@resetPasswordForm')->name('resetPasswordForm');
    Route::post('reset/password/success', 'ForgotPasswordController@resetPassword')->name('resetPassword');


    Route::group(['middleware' => 'admin.auth'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('logout','LoginController@logout')->name('logout');

        Route::get('profile','ProfileController@profile')->name('profile');
        Route::post('update/Profile','ProfileController@updateProfile')->name('updateProfile');

        Route::get('change/password','ChangePasswordController@changePasswordForm')->name('changePasswordForm');
        Route::post('update/password','ChangePasswordController@updatePassword')->name('updatePassword');

        // job posts
        Route::get('job', 'JobPostController@index')->name('job');
        Route::get('add/job', 'JobPostController@addJob')->name('addJob');
        Route::post('store/job', 'JobPostController@storeJob')->name('storeJob');
        Route::get('edit/job/{id}', 'JobPostController@editJob')->name('editJob');
        Route::post('update/job/{id}', 'JobPostController@updateJob')->name('updateJob');
        Route::post('delete/job', 'JobPostController@deleteJob')->name('deleteJob');
        //Route::post('delete/all/jobs', 'JobPostController@deleteAll')->name('deleteAll')->middleware('permission:delete.job');
        Route::get('view/job/candidates/{id}','JobPostController@viewJobCandidates')->name('viewJobCandidates');
        Route::post('sendmail/job/candidates', 'JobPostController@approveJobCandidate')->name('approveJobCandidate');
        Route::post('delete/job/candidates', 'JobPostController@deleteJobCandidate')->name('deleteJobCandidate');
        Route::get('job/candidateresult/{id}','JobPostController@viewJobCandidateResult')->name('viewJobCandidateResult');
        Route::post('changestatus/job', 'JobPostController@changeStatus')->name('changeStatusJob');

        Route::get('upload/job/excel','JobPostController@uploadJobsExcel')->name('uploadJobsExcel');
        Route::post('store/job/excel','JobPostController@storeJobsExcel')->name('storeJobsExcel');

        Route::get('view/job/openings/{id}', 'JobPostController@viewJobOpenings')->name('viewJobOpenings');
        Route::get('add/job/opening/{id}', 'JobPostController@addJobOpening')->name('addJobOpening');
        Route::post('delete/job/opening', 'JobPostController@deleteJobOpening')->name('deleteJobOpening');
        Route::post('store/job/opening', 'JobPostController@storeJobOpening')->name('storeJobOpening');

        //candidate section
        Route::get('candidate','CandidateController@index')->name('candidate');
        Route::post('delete/candidate', 'CandidateController@deleteCandidate')->name('deleteCandidate');
        Route::get('view/candidate/{id}','CandidateController@viewCandidate')->name('viewCandidate');
        Route::post('changestatus/candidate', 'CandidateController@changeStatus')->name('changeStatusCandidate');

        Route::get('candidate/jobs/{id}','CandidateController@jobs')->name('viewCandidateJobs');
        Route::post('delete/candidate/job', 'CandidateController@deleteCandidateJob')->name('deleteCandidateJob');
        Route::post('sendmail/candidate/job', 'CandidateController@approveCandidateJob')->name('approveCandidateJob');
        Route::get('candidate/jobresult/{id}','CandidateController@viewCandidateJobResult')->name('viewCandidateJobResult');

        Route::get('candidate/appointments/{id}','CandidateController@appointments')->name('viewCandidateAppointments');
        Route::post('delete/candidate/appointment', 'CandidateController@deleteAppointment')->name('deleteCandidateAppointment');
        Route::post('approve/candidate/appointments','CandidateController@approveCandidateAppointments')->name('approveCandidateAppointments');
        Route::get('view/appointment/{id}','CandidateController@viewAppointment')->name('viewAppointment');

        //Cms
        Route::get('cms', 'CmsController@index')->name('cms');
        Route::get('add/cms', 'CmsController@addCms')->name('addCms');
        Route::post('store/cms', 'CmsController@storeCms')->name('storeCms');
        Route::get('edit/cms/{id}', 'CmsController@editCms')->name('editCms');
        Route::post('update/cms/{id}', 'CmsController@updateCms')->name('updateCms');

        //Categories
        Route::get('category', 'CategoryController@index')->name('category');
        Route::get('add/category', 'CategoryController@addCategory')->name('addCategory');
        Route::post('store/category', 'CategoryController@storeCategory')->name('storeCategory');
        Route::get('edit/category/{id}', 'CategoryController@editCategory')->name('editCategory');
        Route::post('update/category/{id}', 'CategoryController@updateCategory')->name('updateCategory');
        Route::post('delete/category', 'CategoryController@deleteCategory')->name('deleteCategory');
        Route::post('changestatus/category', 'CategoryController@changeStatus')->name('changeStatusCategory');

        //Enquiry
        Route::get('enquiry','EnquiryController@index')->name('enquiry');
        Route::post('delete/enquiry', 'EnquiryController@deleteEnquiry')->name('deleteEnquiry');

        //City
        Route::get('city','CityController@index')->name('city');
        Route::post('delete/city', 'CityController@deleteCity')->name('deleteCity');
        Route::post('delete/all/cities', 'CityController@deleteAllCities')->name('deleteAllCities');
        Route::get('upload/city/excel','CityController@uploadCitiesExcel')->name('uploadCitiesExcel');
        Route::post('store/city/excel','CityController@storeCitiesExcel')->name('storeCitiesExcel');

        Route::get('view/city/partners/{id}', 'CityController@viewCityPartners')->name('viewCityPartners');
        Route::get('add/city/partner/{id}', 'CityController@addCityPartner')->name('addCityPartner');
        Route::post('delete/city/partner', 'CityController@deleteCityPartner')->name('deleteCityPartner');

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    //
    protected $fillable = ['name'];
}

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\City;
use App\CityPartner;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;

class CityController extends Controller
{
    // City Dashboard
    public function index(){

        $cities = City::get();
        return view('admin.city.index',[ 'cities' => $cities ]);
    }

    // Delete City
    public function deleteCity(Request $request)
    {
        $this->validate($request, [
            'deleteId' => 'required|exists:cities,id'
        ]);
        $city =City::find($request->deleteId);
        $city->delete();
    }

    // Delete All Cities
    public function deleteAllCities(Request $request){

        if($request['cities']!=""){
            $cities = City::wherein('id',$request['cities'])->get();
            foreach ($cities AS $city){
                $city =City::find($city->id);
                $city->delete();
            }
        }

    }

    public function uploadCitiesExcel(){
        return view('admin.city.uploadcitiesexcel');
    }

    // Upload New Cities
    public function storeCitiesExcel(Request $request){

        if($request->file('file') != ""){
            $image = $request->file('file');
            $excel_file = time().$image->getClientOriginalName();
            $destinationPath = base_path('/assets/excelfiles');
            $image->move($destinationPath, $excel_file);
        } else {
            return redirect(route('admin.uploadCitiesExcel'))->with('error','Please upload excel file.');
        }

        $address = "./assets/excelfiles/".$excel_file;

        Excel::load($address, function ($reader) {
            $results = $reader->get();
            foreach ($results->toArray() as $key => $value) {
                if(!empty($value['name'])) {
                    City::create([
                        'name' => $value['name']
                    ]);
                }
            }
        });

        return redirect(route('admin.city'))->with('message','Excel file data uploaded successfully.');


    }

    // view city partners
    public function viewCityPartners($id){
        $citypartners = CityPartner::where(['city_id'=>$id])->get();
        $city = City::find($id);
        return view('admin.city.viewcitypartners',['citypartners' => $citypartners ,'id' => $id ,'city' => $city]);
    }

    // add city partner
    public function addCityPartner($id){
        return view('admin.city.addcitypartner',['id' => $id]);
    }

    // store job opening
    public function storeCityPartner(Request $request){

        $this->validate($request ,array(
            'name' => 'required',
            'email' => 'required',
            'join_date' => 'required',
            'expiry_date' => 'required'
        ));

        CityPartner::create([
            'city_id' => $request->city_id,
            'name' => $request->name,
            'auth_person' => $request->auth_person,
            'address' => $request->address,
            'contact_no' => $request->contact_no,
            'email' => $request->email,
            'bonus' => $request->bonus,
            'join_date' => $request->join_date,
            'expiry_date' => $request->expiry_date,
            'description' => $request->description,
            'reference' => $request->reference,
            'approved_by' => 1,
            'status' => 1
        ]);

        return redirect(route('admin.viewCityPartners',['id' => $request->city_id]))->with('message','City Partner details has been saved successfully.');
    }

    // delete city partner
    public function deleteCityPartner(Request $request){

        $this->validate($request, [
            'cityPartnerId' => 'required|exists:city_partners,id'
        ]);

        $citypartner = CityPartner::find($request->cityPartnerId);
        $citypartner->delete();

    }

}

resources/views/admin/city/index.blade.php
@extends('mainlayout')

@section('title')
    Cities
@endsection

@section('content')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->

            <br/>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="{{ route('admin.dashboard') }}">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Cities</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <br/>
            <img src="{{ asset('assets/loader.gif') }}" style="display: none;" class="loading-img" width="100px" height="100px">
            <!-- BEGIN PAGE CONTENT-->
            <div class="row">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <div class="btn-group">
                                <a class="btn btn-primary delete_all" id="delete_all">
                                    Delete All
                                </a>
                            </div>
                            <div class="btn-group">
                                <a href="{{ route('admin.uploadCitiesExcel') }}" class="btn btn-primary">
                                    Upload Cities
                                </a>
                            </div>
                        </div>
                        <div class="tools"> </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
                            <thead>
                            <tr>
                                <th></th>
                                <th>City Name</th>
                                <th width="145px">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($cities AS $city)
                                <tr>
                                    <td style="text-align: center;">
                                            <input type="checkbox" name="cities[]" value="{{ $city->id }}">
                                    </td>
                                    <td>{{ $city->name }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a class="btn btn-xs green dropdown-toggle" href="javascript:;" data-toggle="dropdown" aria-expanded="true"> Actions
                                                <i class="fa fa-angle-down"></i>
                                            </a>
                                            <ul class="dropdown-menu pull-right">
                                                <li>
                                                    <a  href="{{ route('admin.viewCityPartners',['id' => $city->id]) }}">
                                                        <i class="fa fa-list"></i> View Partners </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;" class="deleteCity" id="deleteCity" data-val="{{ $city->id }}">
                                                        <i class="fa fa-trash-o"></i> Delete </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <!-- END PAGE CONTENT -->
        </div>
    </div>
    <!-- END CONTENT -->

@endsection

@section('js')

    <script type="text/javascript">

        $('.deleteCity').on('click', function(e){
            var deleteId = $(this).attr('data-val');
            swal({
                title: 'Are you sure?',
                text: "You want to Delete this City",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes'
            }).then(function () {
                $.ajax({
                    type: "POST",
                    url: "{{ route('admin.deleteCity') }}",
                    data: {
                        _token: '{{ csrf_token() }}',
                        deleteId: deleteId
                    },
                    success: function (data) {
                        swal({
                            title: 'Success!',
                            text: 'City has been removed Successfully.',
                            type: "success",
                            confirmButtonText: "OK"
                        }).then(function () {
                            location.reload();
                        });
                    },
                    error: function (xhr, status, error) {
                        swal(
                            'Oops !',
                            'Something went wrong, please try again later.',
                            'warning'
                        );
                    }
                });
            });
        });

         $("#delete_all").click(function(){
            var cities = [];
            $.each($("input[name='cities[]']:checked"), function(){
                cities.push($(this).val());
            });

            if(cities != ""){

                swal({
                    title: 'Are you sure?',
                    text: "You want to delete this cities",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes'
                }).then(function () {
                    $.ajax({
                        type: "POST",
                        url: "{{ route('admin.deleteAllCities') }}",
                        data: {
                            _token: '{{ csrf_token() }}',
                            cities: cities
                        },
                        beforeSend:function(){
                            $('.loading-img').css('display','');
                        },
                        success: function (data) {
                            swal({
                                title: 'Success!',
                                text: 'Cities have been deleted successfully.',
                                type: "success",
                                confirmButtonText: "OK"
                            }).then(function () {
                                location.reload();
                            });
                        },
                        error: function (xhr, status, error) {
                            $('.loading-img').css('display','none');
                            swal(
                                'Oops !',
                                'Something went wrong, please try again later.',
                                'warning'
                            );
                        }
                    });
                });

            } else {
                swal(
                    'Oops !',
                    'Please select cities !!',
                    'warning'
                );
            }
        });

    </script>

@endsection

resources/views/admin/city/viewcitypartners.blade.php
@extends('mainlayout')

@section('title')
    City Partners
@endsection

@section('content')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->

            <br/>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="{{ route('admin.dashboard') }}">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="{{ route('admin.city') }}">Cities</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <br/>

            <!-- BEGIN PAGE CONTENT-->
            <div class="row">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <div class="btn-group">
                                <a href="{{ route('admin.addCityPartner',['id' => $id]) }}" class="btn green">
                                    Add City Partner <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                        <div class="tools"> </div>
                    </div>

                    <h3>City Name : {{ $city->name }}</h3>

                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
                            <thead>
                            <tr>
                                <th>Sr. No</th>
                                <th>Name</th>
                                <th>Auth Person</th>
                                <th>Contact No</th>
                                <th>Email ID</th>
                                <th>Bonus</th>
                                <th>Join Date</th>
                                <th>Expiry Date</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(!empty($citypartners))
                                @foreach($citypartners AS $key => $partner)
                                    <tr>
                                        <td style="text-align: center;">
                                            {{ $key + 1 }}
                                        </td>
                                        <td>{{ $partner->name }}</td>
                                        <td>{{ $partner->auth_person }}</td>
                                        <td>{{ $partner->contact_no }}</td>
                                        <td>{{ $partner->email }}</td>
                                        <td>{{ $partner->bonus }}</td>
                                        <td>{{ $partner->join_date }}</td>
                                        <td>{{ $partner->expiry_date }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-xs green dropdown-toggle" href="javascript:;" data-toggle="dropdown" aria-expanded="true"> Actions
                                                    <i class="fa fa-angle-down"></i>
                                                </a>
                                                <ul class="dropdown-menu pull-right">
                                                    <li>
                                                        <a href="javascript:;" class="deleteCityPartner" id="deleteCityPartner" data-val="{{ $partner->id }}">
                                                            <i class="fa fa-trash-o"></i> Delete </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr><td colspan="8">No Records Found.</td></tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <!-- END PAGE CONTENT -->
        </div>
    </div>
    <!-- END CONTENT -->

@endsection

@section('js')

    <script type="text/javascript">

        $('.deleteCityPartner').on('click', function(e){
            var cityPartnerId = $(this).attr('data-val');
            swal({
                title: 'Are you sure?',
                text: "You want to Delete this City Partner",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes'
            }).then(function () {
                $.ajax({
                    type: "POST",
                    url: "{{ route('admin.deleteCityPartner') }}",
                    data: {
                        _token: '{{ csrf_token() }}',
                        cityPartnerId: cityPartnerId
                    },
                    success: function (data) {
                        swal({
                            title: 'Success!',
                            text: 'City Partner has been removed Successfully.',
                            type: "success",
                            confirmButtonText: "OK"
                        }).then(function () {
                            location.reload();
                        });
                    },
                    error: function (xhr, status, error) {
                        swal(
                            'Oops !',
                            'Something went wrong, please try again later.',
                            'warning'
                        );
                    }
                });
            });
        });

    </script>

@endsection