routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'namespace' => 'Website', // it is added in controller function name
    'prefix' => '', //it is added in url
    'as' => 'website.' //route name
], function () {
    Route::get('', 'HomeController@index')->name('home');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::post('contact/email','ContactController@contactEmail')->name('contactEmail');

    Route::get('login', 'LoginController@index')->name('login');
    Route::get('job_details/{id}', 'JobController@index')->name('job_details');

    Route::get('login','LoginController@index')->name('login');
    Route::get('registration', 'RegistrationController@index')->name('registration');
    Route::post('store/candidate','RegistrationController@storeCandidate')->name('storeCandidate');
    Route::post('authenticate','LoginController@authenticate')->name('authenticate');
    Route::get('varify/otp','RegistrationController@otpForm')->name('otpForm');
    Route::post('varify/otp/success','RegistrationController@varifyOtp')->name('varifyOtp');

    // Search Section
    Route::post('view/searchjobs','SearchController@index')->name('searchResult');
    Route::get('view/searchjobs/{title}/{category_id}','SearchController@searchResult')->name('viewSearchResult');

    // Cms
    Route::get('cms/{id}','CmsController@page')->name('cms');

    // Enquiry Section
    Route::get('enquiry','EnquiryController@index')->name('enquiry');
    Route::post('store/enquiry','EnquiryController@storeEnquiry')->name('storeEnquiry');

    // Browse Jobs
    Route::get('browse/jobs','BrowseJobController@index')->name('browseJobs');

    // Browse Categories
    Route::get('browse/categories','BrowseCategoryController@index')->name('browseCategories');
    Route::get('browse/category/jobs/{id}','BrowseCategoryController@categoryJobs')->name('browseCategoryJobs');
    // Job Alert
    Route::get('job/alerts','JobAlertController@index')->name('jobAlerts');

    Route::group(['middleware' => 'candidate.auth'], function () {

      Route::get('logout', 'LoginController@logout')->name('logout');
      Route::get('apply/job/{id}', 'JobController@applyJob')->name('applyJob');

      Route::get('take/appointment','AppointmentController@index')->name('takeAppointment');
      Route::post('get/city/partners','AppointmentController@getCityPartners')->name('getCityPartners');
      Route::post('store/appointment','AppointmentController@storeAppointment')->name('storeAppointment');

      Route::get('book/interview','BookInterviewController@index')->name('bookInterview');
      Route::post('get/category/jobs','BookInterviewController@getCategoryJobs')->name('getCategoryJobs');
      Route::post('store/book/interview','BookInterviewController@storeBookInterview')->name('storeBookInterview');

    });
});



Route::group([
    'namespace' => 'Admin', // it is added in controller function name
    'prefix' => 'admin', //it is added in url
    'as' => 'admin.' //route name
], function () {
    Route::get('','LoginController@loginForm');
    Route::post('authenticate', 'LoginController@authenticate')->name('authenticate');

    Route::get('forgot/password', 'ForgotPasswordController@forgotPasswordEmail')->name('forgotPassword');
    Route::post('verify/email', 'ForgotPasswordController@verifyForgotPasswordEmail')->name('verifyEmail');
    Route::get('reset/password/{token}', 'ForgotPasswordController@resetPasswordForm')->name('resetPasswordForm');
    Route::post('reset/password/success', 'ForgotPasswordController@resetPassword')->name('resetPassword');


    Route::group(['middleware' => 'admin.auth'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('logout','LoginController@logout')->name('logout');

        Route::get('profile','ProfileController@profile')->name('profile');
        Route::post('update/Profile','ProfileController@updateProfile')->name('updateProfile');

        Route::get('change/password','ChangePasswordController@changePasswordForm')->name('changePasswordForm');
        Route::post('update/password','ChangePasswordController@updatePassword')->name('updatePassword');

        // job posts
        Route::get('job', 'JobPostController@index')->name('job');
        Route::get('add/job', 'JobPostController@addJob')->name('addJob');
        Route::post('store/job', 'JobPostController@storeJob')->name('storeJob');
        Route::get('edit/job/{id}', 'JobPostController@editJob')->name('editJob');
        Route::post('update/job/{id}', 'JobPostController@updateJob')->name('updateJob');
        Route::post('delete/job', 'JobPostController@deleteJob')->name('deleteJob');
        //Route::post('delete/all/jobs', 'JobPostController@deleteAll')->name('deleteAll')->middleware('permission:delete.job');
        Route::get('view/job/candidates/{id}','JobPostController@viewJobCandidates')->name('viewJobCandidates');
        Route::post('sendmail/job/candidates', 'JobPostController@approveJobCandidate')->name('approveJobCandidate');
        Route::post('delete/job/candidates', 'JobPostController@deleteJobCandidate')->name('deleteJobCandidate');
        Route::get('job/candidateresult/{id}','JobPostController@viewJobCandidateResult')->name('viewJobCandidateResult');
        Route::post('changestatus/job', 'JobPostController@changeStatus')->name('changeStatusJob');

        Route::get('upload/job/excel','JobPostController@uploadJobsExcel')->name('uploadJobsExcel');
        Route::post('store/job/excel','JobPostController@storeJobsExcel')->name('storeJobsExcel');

        Route::get('view/job/openings/{id}', 'JobPostController@viewJobOpenings')->name('viewJobOpenings');
        Route::get('add/job/opening/{id}', 'JobPostController@addJobOpening')->name('addJobOpening');
        Route::post('delete/job/opening', 'JobPostController@deleteJobOpening')->name('deleteJobOpening');
        Route::post('store/job/opening', 'JobPostController@storeJobOpening')->name('storeJobOpening');

        //candidate section
        Route::get('candidate','CandidateController@index')->name('candidate');
        Route::post('delete/candidate', 'CandidateController@deleteCandidate')->name('deleteCandidate');
        Route::get('view/candidate/{id}','CandidateController@viewCandidate')->name('viewCandidate');
        Route::post('changestatus/candidate', 'CandidateController@changeStatus')->name('changeStatusCandidate');

        Route::get('candidate/jobs/{id}','CandidateController@jobs')->name('viewCandidateJobs');
        Route::post('delete/candidate/job', 'CandidateController@deleteCandidateJob')->name('deleteCandidateJob');
        Route::post('sendmail/candidate/job', 'CandidateController@approveCandidateJob')->name('approveCandidateJob');
        Route::get('candidate/jobresult/{id}','CandidateController@viewCandidateJobResult')->name('viewCandidateJobResult');

        Route::get('candidate/appointments/{id}','CandidateController@appointments')->name('viewCandidateAppointments');
        Route::post('delete/candidate/appointment', 'CandidateController@deleteAppointment')->name('deleteCandidateAppointment');
        Route::post('approve/candidate/appointments','CandidateController@approveCandidateAppointments')->name('approveCandidateAppointments');
        Route::get('view/appointment/{id}','CandidateController@viewAppointment')->name('viewAppointment');

        //Cms
        Route::get('cms', 'CmsController@index')->name('cms');
        Route::get('add/cms', 'CmsController@addCms')->name('addCms');
        Route::post('store/cms', 'CmsController@storeCms')->name('storeCms');
        Route::get('edit/cms/{id}', 'CmsController@editCms')->name('editCms');
        Route::post('update/cms/{id}', 'CmsController@updateCms')->name('updateCms');

        //Categories
        Route::get('category', 'CategoryController@index')->name('category');
        Route::get('add/category', 'CategoryController@addCategory')->name('addCategory');
        Route::post('store/category', 'CategoryController@storeCategory')->name('storeCategory');
        Route::get('edit/category/{id}', 'CategoryController@editCategory')->name('editCategory');
        Route::post('update/category/{id}', 'CategoryController@updateCategory')->name('updateCategory');
        Route::post('delete/category', 'CategoryController@deleteCategory')->name('deleteCategory');
        Route::post('changestatus/category', 'CategoryController@changeStatus')->name('changeStatusCategory');

        //Enquiry
        Route::get('enquiry','EnquiryController@index')->name('enquiry');
        Route::post('delete/enquiry', 'EnquiryController@deleteEnquiry')->name('deleteEnquiry');

        //City
        Route::get('city','CityController@index')->name('city');
        Route::post('delete/city', 'CityController@deleteCity')->name('deleteCity');
        Route::post('delete/all/cities', 'CityController@deleteAllCities')->name('deleteAllCities');
        Route::get('upload/city/excel','CityController@uploadCitiesExcel')->name('uploadCitiesExcel');
        Route::post('store/city/excel','CityController@storeCitiesExcel')->name('storeCitiesExcel');

        Route::get('view/city/partners/{id}', 'CityController@viewCityPartners')->name('viewCityPartners');
        Route::get('add/city/partner/{id}', 'CityController@addCityPartner')->name('addCityPartner');
        Route::post('delete/city/partner', 'CityController@deleteCityPartner')->name('deleteCityPartner');

resources/views/admin/changepassword.blade.php
@extends('mainlayout')

@section('title')
    Change Password
@endsection

@section('content')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
                Change Password
            </h3>
            <br/>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="{{ route('admin.dashboard') }}">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Change Password</a>

                    </li>

                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <br/>
            <!-- BEGIN PAGE CONTENT-->
            <div class="profile-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light">
                            <div class="portlet-title tabbable-line">
                                <div class="caption caption-md">
                                    <i class="icon-globe theme-font hide"></i>
                                    <span class="caption-subject font-blue-madison bold uppercase">Change Password </span>
                                </div>

                            </div>
                            <div class="portlet-body">
                                <div class="tab-content">
                                    <!-- PERSONAL INFO TAB -->

                                    <form role="form" method="post" action="{{ route('admin.updatePassword') }}">

                                        {{ csrf_field() }}
                                        <div class="form-group {{ $errors->has('old_password')? 'has-error':'' }}">
                                            <label class="control-label"> Old Password</label>
                                            <input type="text" placeholder="Old Password" name="old_password" class="form-control">
                                            @if($errors->has('confirm_password'))
                                                <span class="help-block">{{ $errors->first('old_password') }}</span>
                                            @endif
                                        </div>
                                        <div class="form-group  {{ $errors->has('new_password')? 'has-error':'' }}">
                                            <label class="control-label">New Password</label>
                                            <input type="text" placeholder="New Password" name="new_password" class="form-control">
                                            @if($errors->has('confirm_password'))
                                                <span class="help-block">{{ $errors->first('new_password') }}</span>
                                            @endif
                                        </div>

                                        <div class="form-group  {{ $errors->has('confirm_password')? 'has-error':'' }}">
                                            <label class="control-label">Confirm Password</label>
                                            <input type="text" placeholder="Re-enter Password " name="confirm_password"  class="form-control">
                                            @if($errors->has('confirm_password'))
                                                <span class="help-block">{{ $errors->first('confirm_password') }}</span>
                                                @endif
                                        </div>


                                        <div class="margiv-top-10">
                                            <input type="submit"  class="btn green-haze">

                                        </div>
                                    </form>

                                    <!-- END PERSONAL INFO TAB -->
                                    <!-- CHANGE AVATAR TAB -->

                                </div>
                                <!-- END PRIVACY SETTINGS TAB -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    </div>
    <!-- END CONTENT -->
@endsection

resources/views/admin/dashboard.blade.php
@extends('mainlayout')

@section('title')
    Dashboard
@endsection

@section('content')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="index.html">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Dashboard</a>
                    </li>
                </ul>
            </div>
            <h3 class="page-title">
                Dashboard <small>reports & statistics</small>
            </h3>
            <!-- END PAGE HEADER-->
            <!-- BEGIN DASHBOARD STATS -->
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat blue-madison">
                        <div class="visual">
                            <i class="fa fa-comments"></i>
                        </div>
                        <div class="details">
                            <div class="number">
                                {{ $total_jobs }}
                            </div>
                            <div class="desc">
                                Jobs
                            </div>
                        </div>
                        <a class="more" href="{{ route('admin.job') }}">
                            View more <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat red-intense">
                        <div class="visual">
                            <i class="fa fa-bar-chart-o"></i>
                        </div>
                        <div class="details">
                            <div class="number">
                                {{ $total_candidates }}
                            </div>
                            <div class="desc">
                                Members
                            </div>
                        </div>
                        <a class="more" href="{{ route('admin.candidate') }}">
                            View more <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat green-haze">
                        <div class="visual">
                            <i class="fa fa-shopping-cart"></i>
                        </div>
                        <div class="details">
                            <div class="number">
                                {{ $total_appointments }}
                            </div>
                            <div class="desc">
                                Appointments
                            </div>
                        </div>
                        <a class="more" href="{{ route('admin.appointment',['id'=>'pending']) }}">
                            View more <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="dashboard-stat purple-plum">
                        <div class="visual">
                            <i class="fa fa-globe"></i>
                        </div>
                        <div class="details">
                            <div class="number">
                                {{ $total_candidates }}
                            </div>
                            <div class="desc">
                                Resumes
                            </div>
                        </div>
                        <a class="more" href="{{ route('admin.candidate') }}">
                            View more <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
            </div>
            <!-- END DASHBOARD STATS -->
            <div class="clearfix">
            </div>


        </div>
    </div>
    <!-- END CONTENT -->
@endsection

resources/views/admin/forgotpassword.blade.php
@extends('login_mainlayout')


@section('title')
    Forgot Password
@endsection

@section('content')

<!-- BEGIN FORGOT PASSWORD FORM -->
<form class="forget-page" action="{{ route('admin.verifyEmail') }}" method="post">
    {{ csrf_field() }}
    <h3>Forget Password ?</h3>
    <p>
        Enter your e-mail address below to reset your password.
    </p>
    <div class="form-group {{ $errors->has('email')? 'has-error':'' }}">
        <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
        @if($errors->has('email'))
            <span id="name-error" class="help-block help-block-error">{{ $errors->first('email') }}</span>
        @endif
    </div>
    <div class="form-actions">
          <button type="button" id="back-btn" onclick="window.location='{{ url('admin') }}'" class="btn btn-default">Back</button>
        <input type="submit" class="btn btn-success uppercase pull-right" >

    </div>
</form>
<!-- END FORGOT PASSWORD FORM -->

  @endsection

resources/views/admin/login.blade.php
@extends('login_mainlayout')

@section('title')
    Login
@endsection

@section('content')
<!-- BEGIN LOGIN FORM -->
<form class="login-form" action="{{ route('admin.authenticate') }}" method="post">
    {{ csrf_field() }}
    <h3 class="form-title">Sign In</h3>
    <div class="alert alert-danger display-hide">
        <button class="close" data-close="alert"></button>
        <span>
			Enter any username and password. </span>
    </div>
    <div class="form-group {{$errors->has('email')? 'has-error':''}}">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9">Username</label>
        <input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
        @if ($errors->has('email'))
                <span id="name-error" class="help-block help-block-error">{{ $errors->first('email') }}</span>
        @endif
    </div>
    <div class="form-group {{$errors->has('password')?'has-error':'' }}">
        <label class="control-label visible-ie8 visible-ie9">Password</label>
        <input class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password"/>
   @if($errors->has('password'))
            <span id="name-error" class="help-block help-block-error">{{ $errors->first('password') }}</span>
       @endif
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-success uppercase">Login</button>

        {{--<a href="{{ route('admin.forgotPassword') }}" id="forget-password" class="forget-password">Forgot Password?</a>--}}
    </div>
</form>
<!-- END LOGIN FORM -->

  @endsection

resources/views/admin/profile.blade.php
@extends('mainlayout')

@section('title')
    Profile
@endsection

@section('content')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
                Profile
            </h3>
            <br/>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="{{ route('admin.dashboard') }}">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Profile</a>

                    </li>

                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <br/>
            <!-- BEGIN PAGE CONTENT-->
            <div class="profile-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light">
                            <div class="portlet-title tabbable-line">
                                <div class="caption caption-md">
                                    <i class="icon-globe theme-font hide"></i>
                                    <span class="caption-subject font-blue-madison bold uppercase">Profile Details</span>
                                </div>

                            </div>
                            <div class="portlet-body">
                                <div class="tab-content">
                                    <!-- PERSONAL INFO TAB -->

                                        <form role="form" method="post" action="{{ route('admin.updateProfile') }}">

                                            {{ csrf_field() }}
                                            <div class="form-group {{ $errors->has('name')? 'has-error':'' }}">
                                                <label class="control-label"> Name</label>
                                                <input type="text" placeholder="Name" name="name" value="{{ Auth::user()->name }}" class="form-control">
                                                @if ($errors->has('name'))
                                                    <span class="help-block">{{ $errors->first('name') }}</span>
                                                @endif
                                            </div>
                                            <div class="form-group  {{ $errors->has('email')? 'has-error':'' }}">
                                                <label class="control-label">Email</label>
                                                <input type="text" placeholder="Email" name="email" value="{{ Auth::user()->email }}" class="form-control">
                                                @if ($errors->has('email'))
                                                    <span class="help-block">{{ $errors->first('email') }}</span>
                                                @endif
                                            </div>

                                            <div class="form-group  {{ $errors->has('mobile')? 'has-error':'' }}">
                                                <label class="control-label">Mobile No.</label>
                                                <input type="text" placeholder="Mobile No." name="mobile" value="{{ Auth::user()->mobile }}" class="form-control">
                                                @if ($errors->has('mobile'))
                                                    <span class="help-block">{{ $errors->first('mobile') }}</span>
                                                @endif
                                            </div>


                                            <div class="margiv-top-10">
                                               <input type="submit"  class="btn green-haze">

                                            </div>
                                        </form>

                                    <!-- END PERSONAL INFO TAB -->
                                    <!-- CHANGE AVATAR TAB -->

                                    </div>
                                    <!-- END PRIVACY SETTINGS TAB -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END PAGE CONTENT-->
        </div>
    </div>
    <!-- END CONTENT -->
@endsection