routes/web.php
    Route::get('varify/otp','RegistrationController@otpForm')->name('otpForm');
    Route::post('varify/otp/success','RegistrationController@varifyOtp')->name('varifyOtp');

    // Search Section
    Route::post('view/searchjobs','SearchController@index')->name('searchResult');
    Route::get('view/searchjobs/{title}/{category_id}','SearchController@searchResult')->name('viewSearchResult');

    // Cms
    Route::get('cms/{id}','CmsController@page')->name('cms');

    // Enquiry Section
    Route::get('enquiry','EnquiryController@index')->name('enquiry');
    Route::post('store/enquiry','EnquiryController@storeEnquiry')->name('storeEnquiry');

    // Browse Jobs
    Route::get('browse/jobs','BrowseJobController@index')->name('browseJobs');

    // Browse Categories
    Route::get('browse/categories','BrowseCategoryController@index')->name('browseCategories');
    Route::get('browse/category/jobs/{id}','BrowseCategoryController@categoryJobs')->name('browseCategoryJobs');
    // Job Alert
    Route::get('job/alerts','JobAlertController@index')->name('jobAlerts');

    Route::group(['middleware' => 'candidate.auth'], function () {

      Route::get('logout', 'LoginController@logout')->name('logout');
      Route::get('apply/job/{id}', 'JobController@applyJob')->name('applyJob');

      Route::get('take/appointment','AppointmentController@index')->name('takeAppointment');
      Route::post('get/city/partners','AppointmentController@getCityPartners')->name('getCityPartners');
      Route::post('store/appointment','AppointmentController@storeAppointment')->name('storeAppointment');

      Route::get('book/interview','BookInterviewController@index')->name('bookInterview');
      Route::post('get/category/jobs','BookInterviewController@getCategoryJobs')->name('getCategoryJobs');
      Route::post('store/book/interview','BookInterviewController@storeBookInterview')->name('storeBookInterview');

    });
});



Route::group([
    'namespace' => 'Admin', // it is added in controller function name
    'prefix' => 'admin', //it is added in url
    'as' => 'admin.' //route name
], function () {
    Route::get('','LoginController@loginForm');
    Route::post('authenticate', 'LoginController@authenticate')->name('authenticate');

    Route::get('forgot/password', 'ForgotPasswordController@forgotPasswordEmail')->name('forgotPassword');
    Route::post('verify/email', 'ForgotPasswordController@verifyForgotPasswordEmail')->name('verifyEmail');
    Route::get('reset/password/{token}', 'ForgotPasswordController@resetPasswordForm')->name('resetPasswordForm');
    Route::post('reset/password/success', 'ForgotPasswordController@resetPassword')->name('resetPassword');


    Route::group(['middleware' => 'admin.auth'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('logout','LoginController@logout')->name('logout');

        Route::get('profile','ProfileController@profile')->name('profile');
        Route::post('update/Profile','ProfileController@updateProfile')->name('updateProfile');

        Route::get('change/password','ChangePasswordController@changePasswordForm')->name('changePasswordForm');
        Route::post('update/password','ChangePasswordController@updatePassword')->name('updatePassword');

        // job posts
        Route::get('job', 'JobPostController@index')->name('job');
        Route::get('add/job', 'JobPostController@addJob')->name('addJob');
        Route::post('store/job', 'JobPostController@storeJob')->name('storeJob');
        Route::get('edit/job/{id}', 'JobPostController@editJob')->name('editJob');
        Route::post('update/job/{id}', 'JobPostController@updateJob')->name('updateJob');
        Route::post('delete/job', 'JobPostController@deleteJob')->name('deleteJob');
        //Route::post('delete/all/jobs', 'JobPostController@deleteAll')->name('deleteAll')->middleware('permission:delete.job');
        Route::get('view/job/candidates/{id}','JobPostController@viewJobCandidates')->name('viewJobCandidates');
        Route::post('sendmail/job/candidates', 'JobPostController@approveJobCandidate')->name('approveJobCandidate');
        Route::post('delete/job/candidates', 'JobPostController@deleteJobCandidate')->name('deleteJobCandidate');
        Route::get('job/candidateresult/{id}','JobPostController@viewJobCandidateResult')->name('viewJobCandidateResult');
        Route::post('changestatus/job', 'JobPostController@changeStatus')->name('changeStatusJob');

        Route::get('upload/job/excel','JobPostController@uploadJobsExcel')->name('uploadJobsExcel');
        Route::post('store/job/excel','JobPostController@storeJobsExcel')->name('storeJobsExcel');

        Route::get('view/job/openings/{id}', 'JobPostController@viewJobOpenings')->name('viewJobOpenings');
        Route::get('add/job/opening/{id}', 'JobPostController@addJobOpening')->name('addJobOpening');
        Route::post('delete/job/opening', 'JobPostController@deleteJobOpening')->name('deleteJobOpening');
        Route::post('store/job/opening', 'JobPostController@storeJobOpening')->name('storeJobOpening');

        //candidate section
        Route::get('candidate','CandidateController@index')->name('candidate');
        Route::post('delete/candidate', 'CandidateController@deleteCandidate')->name('deleteCandidate');
        Route::get('view/candidate/{id}','CandidateController@viewCandidate')->name('viewCandidate');
        Route::post('changestatus/candidate', 'CandidateController@changeStatus')->name('changeStatusCandidate');

        Route::get('candidate/jobs/{id}','CandidateController@jobs')->name('viewCandidateJobs');
        Route::post('delete/candidate/job', 'CandidateController@deleteCandidateJob')->name('deleteCandidateJob');
        Route::post('sendmail/candidate/job', 'CandidateController@approveCandidateJob')->name('approveCandidateJob');
        Route::get('candidate/jobresult/{id}','CandidateController@viewCandidateJobResult')->name('viewCandidateJobResult');

        Route::get('candidate/appointments/{id}','CandidateController@appointments')->name('viewCandidateAppointments');
        Route::post('delete/candidate/appointment', 'CandidateController@deleteAppointment')->name('deleteCandidateAppointment');
        Route::post('approve/candidate/appointments','CandidateController@approveCandidateAppointments')->name('approveCandidateAppointments');
        Route::get('view/appointment/{id}','CandidateController@viewAppointment')->name('viewAppointment');

        //Cms
        Route::get('cms', 'CmsController@index')->name('cms');
        Route::get('add/cms', 'CmsController@addCms')->name('addCms');
        Route::post('store/cms', 'CmsController@storeCms')->name('storeCms');
        Route::get('edit/cms/{id}', 'CmsController@editCms')->name('editCms');
        Route::post('update/cms/{id}', 'CmsController@updateCms')->name('updateCms');

        //Categories
        Route::get('category', 'CategoryController@index')->name('category');
        Route::get('add/category', 'CategoryController@addCategory')->name('addCategory');
        Route::post('store/category', 'CategoryController@storeCategory')->name('storeCategory');
        Route::get('edit/category/{id}', 'CategoryController@editCategory')->name('editCategory');
        Route::post('update/category/{id}', 'CategoryController@updateCategory')->name('updateCategory');
        Route::post('delete/category', 'CategoryController@deleteCategory')->name('deleteCategory');
        Route::post('changestatus/category', 'CategoryController@changeStatus')->name('changeStatusCategory');

        //Enquiry
        Route::get('enquiry','EnquiryController@index')->name('enquiry');
        Route::post('delete/enquiry', 'EnquiryController@deleteEnquiry')->name('deleteEnquiry');

        //City
        Route::get('city','CityController@index')->name('city');
        Route::post('delete/city', 'CityController@deleteCity')->name('deleteCity');
        Route::post('delete/all/cities', 'CityController@deleteAllCities')->name('deleteAllCities');
        Route::get('upload/city/excel','CityController@uploadCitiesExcel')->name('uploadCitiesExcel');
        Route::post('store/city/excel','CityController@storeCitiesExcel')->name('storeCitiesExcel');

        Route::get('view/city/partners/{id}', 'CityController@viewCityPartners')->name('viewCityPartners');
        Route::get('add/city/partner/{id}', 'CityController@addCityPartner')->name('addCityPartner');
        Route::post('delete/city/partner', 'CityController@deleteCityPartner')->name('deleteCityPartner');
        Route::post('store/city/partner', 'CityController@storeCityPartner')->name('storeCityPartner');

        //Job Locations
        Route::get('joblocation','JobLocationController@index')->name('jobLocation');
        Route::post('delete/joblocation', 'JobLocationController@deleteJobLocation')->name('deleteJobLocation');
        Route::post('delete/all/joblocations', 'JobLocationController@deleteAllJobLocations')->name('deleteAllJobLocations');
        Route::get('upload/joblocation/excel','JobLocationController@uploadJobLocationsExcel')->name('uploadJobLocationsExcel');
        Route::post('store/joblocation/excel','JobLocationController@storeJobLocationsExcel')->name('storeJobLocationsExcel');

        //Appointment
        Route::get('appointment/{id}','AppointmentController@index')->name('appointment');
        Route::post('delete/appointment', 'AppointmentController@deleteAppointment')->name('deleteAppointment');
        Route::post('approve/appointments','AppointmentController@approveAppointments')->name('approveAppointments');
        Route::get('view/appointment/{id}','AppointmentController@viewAppointment')->name('viewAppointment');

        //Clients & Partners
        Route::get('partner','ClientPartnerController@index')->name('clientPartners');
        Route::get('add/partner', 'ClientPartnerController@addClientPartner')->name('addClientPartner');

app/Jobpost.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jobpost extends Model
{
    //
    protected $fillable = ['job_title','job_description','short_description','image','salary','job_type','start_date','end_date','company_title','education','experiences','skills','responsibilities','place','approved_by','status','category_id'];

     public function category()
  {
      return $this->belongsTo(Category::class, 'category_id', 'id');
  }

}

resources/views/admin/jobpost/addjobopening.blade.php
@extends('mainlayout')

@section('title')
    Add Job Opening
@endsection

@section('content')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <br/>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="{{ route('admin.dashboard') }}">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="{{ route('admin.job') }}">Job</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Add</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <br/>
            <!-- BEGIN PAGE CONTENT-->
            <div class="row">
                <div class="col-md-12">
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_1">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-gift"></i>Add New Job Opening
                                    </div>
                                    <div class="tools">
                                        <a href="javascript:;" class="collapse">
                                        </a>
                                        <a href="#portlet-config" data-toggle="modal" class="config">
                                        </a>
                                        <a href="javascript:;" class="reload">
                                        </a>
                                        <a href="javascript:;" class="remove">
                                        </a>
                                    </div>
                                </div>
                                <div class="portlet-body form">
                                    <!-- BEGIN FORM-->
                                    <form class="horizontal-form" method="post" action="{{ route('admin.storeJobOpening') }}" enctype="multipart/form-data">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="jobpost_id" id="jobpost_id" value="{{ $id }}">
                                        <div class="form-body">

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group {{ $errors->has('company_name') ? 'has-error' : '' }}">
                                                        <label class="control-label">Company Name</label>
                                                        <input type="text" name="company_name" id="company_name" class="form-control"  value="{{ old('company_name') }}">
                                                        @if ($errors->has('company_name'))
                                                            <span class="help-block">{{ $errors->first('company_name') }}</span>
                                                        @endif
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group {{ $errors->has('start_date') ? 'has-error' : '' }}">
                                                        <label class="control-label">Start Date</label>
                                                        <input type="text" data-date-start-date="-{{ date('d') - 1 }}d" data-date="2012-02-12" data-date-format="yyyy-mm-dd" name="start_date" id="start_date" class="form-control date-picker" placeholder="yyyy-mm-dd" value="{{ old('start_date') }}" readonly>
                                                        @if ($errors->has('start_date'))
                                                            <span class="help-block">{{ $errors->first('start_date') }}</span>
                                                        @endif
                                                    </div>
                                                </div>

                                                <div class="col-md-6">
                                                    <div class="form-group {{ $errors->has('end_date') ? 'has-error' : '' }}">
                                                        <label class="control-label">End Date</label>
                                                        <input type="text" data-date-start-date="-{{ date('d') - 1 }}d" data-date="2012-02-12" data-date-format="yyyy-mm-dd" name="end_date" id="end_date" class="form-control date-picker" placeholder="yyyy-mm-dd" value="{{ old('end_date') }}" readonly>
                                                        @if ($errors->has('end_date'))
                                                            <span class="help-block">{{ $errors->first('end_date') }}</span>
                                                        @endif
                                                    </div>
                                                </div>
                                                <!--/span-->
                                            </div>

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group {{ $errors->has('start_time') ? 'has-error' : '' }}">
                                                        <label class="control-label">Start Time</label>
                                                        <input type="text" name="start_time" id="start_time" class="form-control timepicker"  value="{{ old('start_time') }}">
                                                        @if ($errors->has('start_time'))
                                                            <span class="help-block">{{ $errors->first('start_time') }}</span>
                                                        @endif
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group {{ $errors->has('end_time') ? 'has-error' : '' }}">
                                                        <label class="control-label">End Time</label>
                                                        <input type="text" name="end_time" id="end_time" class="form-control timepicker"  value="{{ old('end_time') }}">
                                                        @if ($errors->has('end_time'))
                                                            <span class="help-block">{{ $errors->first('end_time') }}</span>
                                                        @endif
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-12 ">
                                                    <div class="form-group">
                                                        <label>Location</label>
                                                        <textarea class="ckeditor form-control" name="location" rows="6">{{ old('location') }}</textarea>
                                                    </div>
                                                </div>
                                            </div>

                                            <!--/span-->
                                        </div>
                                        <div class="form-actions right">
                                            <a href="{{ route('admin.viewJobOpenings',['id' => $id]) }}"><button type="button" class="btn default">Cancel</button></a>
                                            <button type="submit" class="btn blue"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    <!-- END FORM-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END PAGE CONTENT-->
        </div>
    </div>
    <!-- END CONTENT -->
@endsection

@section('js')

    <script type="text/javascript">
        $('.timepicker').timepicker();
    </script>

@endsection

resources/views/admin/jobpost/index.blade.php
@extends('mainlayout')

@section('title')
    Jobs
@endsection

@section('content')
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->

            <br/>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="{{ route('admin.dashboard') }}">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="{{ route('admin.job') }}">Jobs</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <br/>
            <!-- BEGIN PAGE CONTENT-->
            <div class="row">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <div class="btn-group">
                                    <a href="{{ route('admin.addJob')  }}" class="btn green">
                                        Add New Job <i class="fa fa-plus"></i>
                                    </a>
                            </div>
                            <div class="btn-group">
                                <a href="{{ route('admin.uploadJobsExcel')  }}" class="btn green">
                                    Upload Jobs Using Excel <i class="fa fa-upload"></i>
                                </a>
                            </div>
                        </div>
                        <div class="tools"> </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
                            <thead>
                            <tr>
                                <th>Sr. No.</th>
                                <th>Category Name</th>
                                <th>Job Title</th>
                                <th>Image</th>
                                <th>Job Type</th>
                                <th>Salary</th>
                                <th>Status</th>
                                <th width="145px">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                          <?php  $i=1;?>
                            @foreach($jobs AS $i=>$job)
                                <tr>
                                    <td>{{ $i+1 }}</td>
                                    <td>{{ $job->category->name }}</td>
                                    <td>{{ $job->job_title }}</td>
                                    @if($job->image!="")
                                        <td><img src="{{ asset('assets/images/job/'.$job->image) }}" width="100px" height="100px"></td>
                                    @else
                                        <td><img src="{{ asset('assets/img/no-image.png') }}" width="100px" height="100px"></td>
                                    @endif
                                    <td>{{ $job->job_type }}</td>
                                    <td>{{ $job->salary }}</td>
                                    <td style="text-align: center;"> <button type="button" data-val="{{ $job->id }}"
                                                                             id="status_{{ $job->id }}"
                                                                             class="status_check {{ ($job['status']) ? 'uk-badge uk-badge-success' : 'uk-badge uk-badge-danger'}}"
                                                                             value="{{$job->status}}">{{ ($job['status']) ? 'Active' : 'Inactive'}}
                                        </button></td>
                                    <td>
											<div class="btn-group">
                                                <a class="btn btn-xs green dropdown-toggle" href="javascript:;" data-toggle="dropdown" aria-expanded="true"> Actions
                                                    <i class="fa fa-angle-down"></i>
                                                </a>
                                                <ul class="dropdown-menu pull-right">
                                                    <li>
                                                        <a href="{{ route('admin.viewJobCandidates',['id' => $job->id]) }}">
                                                            <i class="fa fa-list"></i> Candidates </a>
                                                    </li>
                                                    <li>
                                                        <a  href="{{ route('admin.viewJobOpenings',['id' => $job->id]) }}">
                                                            <i class="fa fa-list"></i> Opening </a>
                                                    </li>
                                                    <li>
                                                        <a  href="{{ route('admin.editJob',['id' => $job->id]) }}">
                                                            <i class="fa fa-pencil"></i> Edit </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;" class="deleteJob" id="deleteJob" data-val="{{ $job->id }}">
                                                            <i class="fa fa-trash-o"></i> Delete </a>
                                                    </li>
                                                   
                                                </ul>
                                            </div>
                                     </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <!-- END PAGE CONTENT -->
        </div>
    </div>
    <!-- END CONTENT -->

@endsection

@section('js')
    <script type="text/javascript">

    $('.status_check').click(function () {
        var status = parseInt($(this).val());
        var jobId = $(this).attr('data-val');

        swal({
            title: 'Are you sure?',
            text: "You want to " + (status ? 'De-Activate' : 'Activate') + " this Job!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes'
        }).then(function () {
            $.ajax({
                type: "POST",
                url: "{{ route('admin.changeStatusJob') }}",
                data: {
                    _token: '{{ csrf_token() }}',
                    status: status,
                    jobId: jobId
                },
                beforeSend:function(){
                    $('.loading-img').css('display','');
                },
                success: function (data) {
                    var element = $('#status_' + jobId);
                    if (data['status']) {
                        element.html('Active')
                            .removeClass('uk-badge uk-badge-danger')
                            .addClass('uk-badge uk-badge-success');
                    } else {
                        element.html('Inactive')
                            .removeClass('uk-badge uk-badge-success')
                            .addClass('uk-badge uk-badge-danger');
                    }
                    element.val(data['status']);
                    $('.loading-img').css('display','none');
                    swal(
                        (status ? 'De-Activated' : 'Activated') + '!',
                        'Job has been ' + (status ? 'De-Activated' : 'Activated') + ' .',
                        "success"
                    );
                },
                error: function (xhr, status, error) {
                    swal(
                        'Oops !',
                        'Something went wrong, please try again later.',
                        'warning'
                    );
                }
            });
        });
    });

    $('.deleteJob').on('click', function(e){
    var jobId = $(this).attr('data-val');
    swal({
        title: 'Are you sure?',
        text: "You want to Delete this Job",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes'
    }).then(function () {
    $.ajax({
        type: "POST",
        url: "{{ route('admin.deleteJob') }}",
        data: {
            _token: '{{ csrf_token() }}',
            jobId: jobId
        },
        success: function (data) {
            swal({
                title: 'Success!',
                text: 'Job has been removed Successfully.',
                type: "success",
                confirmButtonText: "OK"
            }).then(function () {
                location.reload();
            });
        },
        error: function (xhr, status, error) {
            swal(
                'Oops !',
                'Something went wrong, please try again later.',
                'warning'
            );
        }
    });

    });
    });
    </script>
@endsection